name: cryptodart
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
 path: ^1.6.0
 args: ^1.5.2
 steel_crypt: ^1.7.1+1
 crypto: ^2.1.4
#  encrypt: ^4.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
